#!/bin/bash

# GitHub Release Creation Guide for Port Manager
# Since gh CLI is not installed, follow these manual steps:

echo "==================================================================="
echo "GitHub Release Creation Steps for Port Manager v1.0.0"
echo "==================================================================="
echo ""
echo "1. Open your browser and go to:"
echo "   https://github.com/pradeepmdk/Port-Manager-Mac/releases/new"
echo ""
echo "2. Fill in the release form:"
echo "   - Tag version: v1.0.0"
echo "   - Target: main"
echo "   - Release title: Port Manager v1.0.0"
echo ""
echo "3. Copy and paste this description:"
echo "-------------------------------------------------------------------"
cat /Users/pradeepkumar/Documents/Projects/personal/erolabs/Port-Manager-Mac/RELEASE_NOTES.md
echo "-------------------------------------------------------------------"
echo ""
echo "4. Upload the DMG file as an asset:"
echo "   File location: $(pwd)/PortManager-v1.0.0.dmg"
echo "   File size: $(ls -lh PortManager-v1.0.0.dmg | awk '{print $5}')"
echo ""
echo "5. Check these options:"
echo "   ✓ Set as the latest release"
echo "   ✓ Create a discussion for this release (optional)"
echo ""
echo "6. Click 'Publish release'"
echo ""
echo "==================================================================="
echo "Alternative: Install GitHub CLI for automated releases"
echo "==================================================================="
echo ""
echo "If you want to automate this in the future, install GitHub CLI:"
echo "   brew install gh"
echo ""
echo "Then you can create releases with:"
echo "   gh release create v1.0.0 PortManager-v1.0.0.dmg \\"
echo "     --title 'Port Manager v1.0.0' \\"
echo "     --notes-file RELEASE_NOTES.md"
echo ""
